site_name: 张奕庆的个人网站
theme:
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - search.highlight
    - navigation.tabs
    - navigation.indexes
    - navigation.path
    - navigation.expand

  name: material
  language: zh
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - 我: 
    - 个人简介: Me/introduction.md
    - 教育经历: Me/education.md
    - 外语能力: Me/language.md
  - 电影: 
    - 关于电影: Movie/movie.md
  - 旅行: 
    - 关于旅行: Travel/travel.md
    - 日本印象: 
      - 大阪: Travel/osaka.md
    - 日本游推荐:
      - 值得专程造访: Travel/3star.md
      - 值得绕道前往: Travel/2star.md
      - 值得驻足: Travel/1star.md
  - 偶像: Idol/Idol.md
  - 游戏:
    - 关于游戏: Game/game.md
    # - 游戏评价:
    #  - 极品飞车(2015): Game/NFS/NFS.md
  - 日志: maintenance.md
plugins:
  - blog
  - search
  - glightbox
markdown_extensions:
  - attr_list
  - md_in_html
copyright: Copyright &copy; 2024 - 2024 张奕庆
